#include <pgm.h>

#include <stdlib.h>
#include <stdio.h> 
#include <string.h>



#if ((0x100 & 0xf) == 0x0)
#define I_M_LITTLE_ENDIAN 1
#define swap(mem) (( (mem) & (short int)0xff00) >> 8) +	\
  ( ((mem) & (short int)0x00ff) << 8)
#else
#define I_M_LITTLE_ENDIAN 0
#define swap(mem) (mem)
#endif








char write_pgm( pgm *output_img, const char *image_name) {
	
	unsigned int elements = output_img->width * output_img->height;
	if ( ( output_img->maxval > 255 ) && I_M_LITTLE_ENDIAN) {
		for (unsigned int i=0; i<elements; ++i) {
			
			((uint16_t*) output_img->data)[i] = swap(  ((uint16_t*) output_img->data)[i] );
			
		}
		
	}
	
	FILE* image_file; 
	image_file = fopen(image_name, "w"); 
	fprintf(image_file, "P5\n# generated by\n# giuliodondi\n%d %d\n%d\n", output_img->width, output_img->height, output_img->maxval);
	
	unsigned int img_size =  elements*(1 + (output_img->maxval > 255));
	

	if (! fwrite( output_img->data , 1, img_size, image_file) ) {
		printf("Error writing image.\n");
		clear_pgm(output_img);
		fclose(image_file);
		return -1;
	}


	fclose(image_file); 
	return 0;

}


char read_pgm( pgm* input_img, const char *image_name) {
	
	input_img->width=0;
	input_img->height=0;
	input_img->maxval = 0;
	input_img->data=NULL;
	
	
	FILE* image_file; 
	image_file = fopen(image_name, "r"); 



	char    MagicN[2];
	char   *line = NULL;
	size_t  k, n = 0;
  
	// get the Magic Number
	k = fscanf(image_file, "%2s%*c", MagicN );
	
	if (strcmp(MagicN, "P5")) {
		printf("Error: the image is not PGM.\n");
		return -1;
	}

 	// skip all the comments
	k = getline( &line, &n, image_file);
	while ( (k > 0) && (line[0]=='#') ) {
    	k = getline( &line, &n, image_file);
	}
	
	if (k<=0) {
	  	printf("Error while reading the image header.\n");
	  	free( line );
		fclose(image_file);
	  	return -1;
	}
	
	k = sscanf(line, "%d%*c%d%*c%d%*c", &input_img->width, &input_img->height, &input_img->maxval);
	if (k<=0) {
	  	printf("Error while reading the image header.\n");
	  	free( line );
		fclose(image_file);
	  	return -1;
	}
	else if ( k < 3 ) {
		k = fscanf(image_file, "%d%*c", &input_img->maxval);
	} 
	  
	free( line );
	
	
	unsigned int elements = input_img->width * input_img->height;
	unsigned int img_size =  elements*(1 + (input_img->maxval > 255));
	
	
	//allocate memory 
	
	
	
	input_img->data = (uint8_t*)malloc( img_size*sizeof(uint8_t) );
	if (! input_img->data) {
		printf("Error during memory allocation.\n");
		clear_pgm(input_img);
		fclose(image_file);
		return -1;
	}
	
	if ( fread( input_img->data , 1, img_size, image_file) != img_size )     {
      printf("Error reading image.\n");
	clear_pgm(input_img);
	fclose(image_file);
	return -1;
    }  

	
	
	//take care of endianness
	
	
	if ( ( input_img->maxval > 255 ) && I_M_LITTLE_ENDIAN) {
		for (unsigned int i=0; i<elements; ++i) {
			((uint16_t*) input_img->data)[i] = swap(  ((uint16_t*) input_img->data)[i] );
		}
	}
		

	
	fclose(image_file);
	return 0;
}





void copy_pgm( pgm *image1, pgm* image2) {
	
	image2->width = image1->width;
	image2->height = image1->height;
	image2->maxval = image1->maxval;
	
	if (image2->data) {
		free(image2->data);
	}
	
	unsigned int elements = image1->width * image1->height;
	unsigned int img_size =  elements*(1 + (image1->maxval > 255));
	
	image2->data = (uint8_t*)malloc( img_size*sizeof(uint8_t) );
	
	memcpy( image2->data , image1->data, img_size*sizeof(uint8_t)  );

}


void clear_pgm( pgm *image) {
	
	image->width=0;
	image->height=0;
	image->maxval = 0;
	
	if (image->data) {
		free(image->data);
		image->data=NULL;
	}
	
	
	
}

